### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by kagecom** [aushani/tsf#2]
Hello,

i follow the README when doing "bazel build //...", it reports errors. 

However, the erros are different when doing the compilation commands multiple times.

some errors are,

1. 

 Linking of rule '//library/kitti/nodes:nodes' failed (Exit 1)
/usr/bin/ld: bazel-out/k8-fastbuild/bin/library/kitti/nodes/_objs/nodes/library/kitti/nodes/kitti_pose.pic.o: undefined reference to symbol 'sqrt@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

2.
ERROR: /home/kage/project/tsf/cc/library/viewer/util/BUILD:1:1: Linking of rule '//library/viewer/util:util' failed (Exit 1)
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
bazel-out/k8-fastbuild/bin/library/viewer/util/_objs/util/library/viewer/util/utils.pic.o: In function `so3_rotxyz(double*, double const*)':
utils.cpp:(.text+0x4f): undefined reference to `_fsincos(double, double*, double*, char const*, char const*, unsigned int)'
utils.cpp:(.text+0x8d): undefined reference to `_fsincos(double, double*, double*, char const*, char const*, unsigned int)'
utils.cpp:(.text+0xcb): undefined reference to `_fsincos(double, double*, double*, char const*, char const*, unsigned int)'
bazel-out/k8-fastbuild/bin/library/viewer/util/_objs/util/library/viewer/util/utils.pic.o: In function `ViewerUtils::setup_qt_threading(osg::ArgumentParser&)':
utils.cpp:(.text+0x5ab): undefined reference to `osg::ArgumentParser::read(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
utils.cpp:(.text+0x608): undefined reference to `osg::ArgumentParser::read(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
utils.cpp:(.text+0x665): undefined reference to `osg::ArgumentParser::read(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
utils.cpp:(.text+0x6c2): undefined reference to `osg::ArgumentParser::read(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
utils.cpp:(.text+0x6fe): undefined reference to `QCoreApplication::setAttribute(Qt::ApplicationAttribute, bool)'
collect2: error: ld returned 1 exit status

3.
ERROR: /home/kage/project/tsf/cc/library/util/BUILD:1:1: Linking of rule '//library/util:util' failed (Exit 1)
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
bazel-out/k8-fastbuild/bin/library/util/_objs/util/library/util/util.pic.o: In function `load_velodyne_file(char const*, float*)':
util.cc:(.text+0x1a3): undefined reference to `velodyne_returns_create'
collect2: error: ld returned 1 exit status

or so on

i think some thing wrong with the build file, can you tell me what is wrong??

**Comment by kagecom** [comment]
i build the project in ubuntu 16.04

**Comment by aushani** [comment]
I'm having trouble reproducing this error, could you tell me a bit more? What versions of g++, bazel do you have? Did you run the bootstrap script?

Can you narrow down which parts of the code are causing problems? For example `bazel build //library/util` just to compile the util library.
